version: '3.8'

services: 
  db:
    image: postgres:16.3-alpine
    container_name: pos_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: POS
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.8 
    container_name: pgadmin_app
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=nuke@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
      - PGADMIN_LISTEN_PORT=80 # Internal container port (usually 80)
    
    ports:
      - "8080:80" 
      

volumes:
  postgres_data: