version: "3.8"

services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "3001:3001"
    environment: # เพิ่ม: Environment Variables ที่ Backend ต้องการ
      PORT: "3001"
      DATABASE_URL: "postgres://admin:12345@db:5432/POS"
      ACCESS_JWT_SECRET: "your acces secret"
      REFRESH_JWT_SECRET: "your refresh secret"
      FRONT_END: "http://localhost:3000"
      NODE_ENV: "dev"
    networks:
      - backend_network
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    container_name: pos_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: POS
    ports:
      - 5432:5432
    volumes:
      - dev:/var/lib/postgresql/data

    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin_app

    environment:
      - PGADMIN_DEFAULT_EMAIL=nuke@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
      - PGADMIN_LISTEN_PORT=80 # Internal container port (usually 80)

    ports:
      - "8080:80"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  dev:
