version: "3.8"

services:
  backend:
    build: ./
    container_name: backend
    ports:
      - 3001:3001
    environment: # เพิ่ม: Environment Variables ที่ Backend ต้องการ
      PORT: "3001"
      DATABASE_URL: "postgres://admin:12345@db:5432/POS"
      ACCESS_JWT_SECRET: "your access secret"
      REFRESH_JWT_SECRET: "your refresh secret"
      FRONT_END: "http://localhost:3000"
      NODE_ENV: "dev"
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run seed &&npm run dev"

  db:
    image: postgres:16.3-alpine
    container_name: pos_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: POS
    ports:
      - 5432:5432
    volumes:
      - dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d review_restaurant"] # ตรวจสอบว่า DB พร้อมรับ Connection
      interval: 5s # ตรวจสอบทุก 5 วินาที
      timeout: 5s # Timeout 5 วินาที
      retries: 5 # ลอง 5 ครั้งก่อนประกาศว่าไม่ healthy
      start_period: 10s # รอ 10 วินาทีแรกก่อนเริ่ม Health Check

    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin_app

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
      - PGADMIN_LISTEN_PORT=80 # Internal container port (usually 80)

    ports:
      - "8080:80"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  dev:
